#ifndef ERROR_H
#define ERROR_H

typedef enum {
    FB_ERR_NONE = 0,
    FB_ERR_NEXT_WITHOUT_FOR = 1,
    FB_ERR_SYNTAX = 2,
    FB_ERR_RETURN_WITHOUT_GOSUB = 3,
    FB_ERR_OUT_OF_DATA = 4,
    FB_ERR_ILLEGAL_FUNC_CALL = 5,
    FB_ERR_OVERFLOW = 6,
    FB_ERR_OUT_OF_MEMORY = 7,
    FB_ERR_UNDEFINED_LABEL = 8,
    FB_ERR_SUBSCRIPT_OUT_OF_RANGE = 9,
    FB_ERR_DUPLICATE_DEFINITION = 10,
    FB_ERR_DIVISION_BY_ZERO = 11,
    FB_ERR_ILLEGAL_IN_DIRECT = 12,
    FB_ERR_TYPE_MISMATCH = 13,
    FB_ERR_OUT_OF_STRING_SPACE = 14,
    FB_ERR_STRING_TOO_LONG = 15,
    FB_ERR_STRING_FORMULA_TOO_COMPLEX = 16,
    FB_ERR_CANT_CONTINUE = 17,
    FB_ERR_UNDEFINED_FUNCTION = 18,
    FB_ERR_NO_RESUME = 19,
    FB_ERR_RESUME_WITHOUT_ERROR = 20,
    FB_ERR_UNPRINTABLE_ERROR = 22,
    FB_ERR_MISSING_OPERAND = 23,
    FB_ERR_LINE_BUFFER_OVERFLOW = 24,
    FB_ERR_DEVICE_TIMEOUT = 25,
    FB_ERR_DEVICE_FAULT = 26,
    FB_ERR_OUT_OF_PAPER = 27,
    FB_ERR_WHILE_WITHOUT_WEND = 29,
    FB_ERR_WEND_WITHOUT_WHILE = 30,
    FB_ERR_DUPLICATE_LABEL = 33,
    FB_ERR_SUBPROGRAM_NOT_DEFINED = 35,
    FB_ERR_ARGUMENT_COUNT_MISMATCH = 37,
    FB_ERR_ARRAY_NOT_DEFINED = 38,
    FB_ERR_VARIABLE_REQUIRED = 40,
    FB_ERR_FIELD_OVERFLOW = 50,
    FB_ERR_INTERNAL_ERROR = 51,
    FB_ERR_BAD_FILE_NUMBER = 52,
    FB_ERR_FILE_NOT_FOUND = 53,
    FB_ERR_BAD_FILE_MODE = 54,
    FB_ERR_FILE_ALREADY_OPEN = 55,
    FB_ERR_FIELD_STATEMENT_ACTIVE = 56,
    FB_ERR_DEVICE_IO_ERROR = 57,
    FB_ERR_FILE_ALREADY_EXISTS = 58,
    FB_ERR_BAD_RECORD_LENGTH = 59,
    FB_ERR_DISK_FULL = 61,
    FB_ERR_INPUT_PAST_END = 62,
    FB_ERR_BAD_RECORD_NUMBER = 63,
    FB_ERR_BAD_FILE_NAME = 64,
    FB_ERR_TOO_MANY_FILES = 67,
    FB_ERR_DEVICE_UNAVAILABLE = 68,
    FB_ERR_COMMUNICATION_BUFFER_OVERFLOW = 69,
    FB_ERR_PERMISSION_DENIED = 70,
    FB_ERR_DISK_NOT_READY = 71,
    FB_ERR_DISK_MEDIA_ERROR = 72,
    FB_ERR_FEATURE_UNAVAILABLE = 73,
    FB_ERR_RENAME_ACROSS_DISKS = 74,
    FB_ERR_PATH_FILE_ACCESS_ERROR = 75,
    FB_ERR_PATH_NOT_FOUND = 76,
} FBErrorCode;

void fb_error(FBErrorCode code, int line, const char* extra_msg);
void fb_syntax_error(int line, int col, const char* msg);
const char* fb_error_message(FBErrorCode code);

/* Global error state (for ON ERROR/ERR/ERL) */
extern int fb_last_error_code;
extern int fb_last_error_line;

#endif
