' Phase 2: String functions test
PRINT LEN("Hello")
PRINT LEFT$("Hello World", 5)
PRINT RIGHT$("Hello World", 5)
PRINT MID$("Hello World", 7)
PRINT MID$("Hello World", 7, 3)
PRINT UCASE$("hello")
PRINT LCASE$("HELLO")
PRINT LTRIM$("  hello  ")
PRINT RTRIM$("  hello  ")
PRINT CHR$(65)
PRINT ASC("A")
PRINT STR$(42)
PRINT VAL("3.14")
PRINT INSTR("Hello World", "World")
PRINT STRING$(5, "*")
PRINT SPACE$(3); "X"
PRINT HEX$(255)
PRINT OCT$(255)
